In [3]:
import torch
import numpy as np

In [16]:
# tensor 和 numpy 对象的相互转化
a = np.array([[1, 2, 3], [4, 5, 6]])
b = torch.tensor(a)
c = b.numpy()
type(a), type(b), type(c)

(numpy.ndarray, torch.Tensor, numpy.ndarray)

In [15]:
# 只有一个元素的向量可以转化为标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [23]:
# reshape的一些特性
a = torch.arange(12)
b = a.reshape(3, 4)
b[:] = 2    # 修改所有的值
a, b   # 地址没有改变，实在原地址上进行操作，但是形状又不一样

(tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 tensor([[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]]))