In [3]:
import numpy as np
import torch

In [6]:
matrix = torch.arange(20).reshape(5, 4)
matrix

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
matrix.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
matrix = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
matrix

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
matrix == matrix.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()   # 分配一个新内存，将A的一个副本赋值给B
A, A+B, A*B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225],
         [256, 289, 324, 361]]))

In [21]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))